#!/bin/bash

# DO NOT FORGET TO DISABLE ALL THE JAVA OPTIONS IN NETSCAPE
# OTHERWISE IT WILL DIE ...

outputFile=sysInfo.out

NODE_NAME=`uname -n`
echo "node_name="$NODE_NAME > $outputFile

DOMAINNAME="`hostname --domain`"
echo "domainname="$DOMAINNAME >> $outputFile

KERNEL_NAME="`uname -s`"
echo "kernel_name="$KERNEL_NAME >> $outputFile

KERNEL_RELEASE="`uname -r`"
echo "kernel_release="$KERNEL_RELEASE >> $outputFile

KERNEL_VERSION="`uname -v`"
echo "kernel_version="$KERNEL_VERSION >> $outputFile

MACHINE="`uname -m`"
echo "machine="$MACHINE >> $outputFile


# not available anymore in uname version 5 and newer
PROCESSOR="`uname -p`"
echo "processor="$PROCESSOR >> $outputFile

# not available anymore in uname version 5 and newer
HARDWARE_PLATFORM="`uname -i`"
echo "hardware_platform="$HARDWARE_PLATFORM >> $outputFile

OPERATING_SYSTEM="`uname -o`"
echo "operating_system="$OPERATING_SYSTEM >> $outputFile


#export $NODE_NAME 
#export $NODE_NAME $DOMAINNAME $KERNEL_NAME $KERNEL_RELEASE $KERNEL_VERSION $MACHINE $PROCESSOR $HARDWARE_PLATFORM $OPERATING_SYSTEM



#/sbin/lilo -C "$liloConf"

