#!/bin/sh
# Released under the GPL
# pmf - 2008/07/31

# This script runs LTTV in place in the compile directory without need for installing it with make install.
# 
# The .runlttvrc file can be used to control its behavior.
# - by setting the TRACEFILE variable, a trace can be automatically loaded
#     ex: TRACEFILE="-t /tmp/traces/dijkstra-20071212"
# - by setting the ARGS variable, a different set of plugins can be loaded
#     for an example see the ARGS= line below
#
# In order for icons to display correctly, it might be necessary to create a symlink:
#   $ ln -s ./lttv/modules/gui/lttvwindow/pixmaps
# while in the same directory as this script.

RCFILE=".runlttvrc"

ARGS="-L lttv/modules/gui/controlflow/.libs -m guicontrolflow -L lttv/modules/gui/lttvwindow/lttvwindow/.libs -m lttvwindow -L lttv/modules/gui/detailedevents/.libs -m guievents -L lttv/modules/gui/tracecontrol/.libs -m guitracecontrol -L lttv/modules/gui/statistics/.libs -m guistatistics -L lttv/modules/gui/resourceview/.libs -m resourceview -L lttv/modules/gui/filter/.libs -m guifilter -L lttv/modules/gui/interrupts/.libs -m interrupts -L lttv/modules/gui/histogram/.libs -m guihistogram"

if [ -e "$RCFILE" ]; then
	source "$RCFILE";
fi

if [ "$1" = "dbg" ]; then
	LD_LIBRARY_PATH=ltt/.libs gdb --args lttv/lttv/.libs/lttv.real $ARGS $TRACEFILE
elif [ "$1" = "valgrind" ]; then
	LD_LIBRARY_PATH=ltt/.libs valgrind lttv/lttv/.libs/lttv.real $ARGS $TRACEFILE
elif [ "$1" = "strace" ]; then
	LD_LIBRARY_PATH=ltt/.libs strace lttv/lttv/.libs/lttv.real $ARGS $TRACEFILE
else
	LD_LIBRARY_PATH=ltt/.libs lttv/lttv/.libs/lttv.real $ARGS $TRACEFILE
fi
